---

- name: k8s dashboard
  shell: kubectl apply -f https://gist.githubusercontent.com/initcron/32ff89394c881414ea7ef7f4d3a1d499/raw/baffda78ffdcaf8ece87a76fb2bb3fd767820a3f/kube-dashboard.yaml

- name: Get node port
  shell: kubectl describe svc kubernetes-dashboard -n kube-system
  register: result

- name: set node port
  set_fact:
    nodeport: "{{ result.stdout }}"

- debug:
  msg: "{{ nodeport }}"
