---

- name: k8s dashboard
  shell: kubectl apply -f https://gist.githubusercontent.com/initcron/32ff89394c881414ea7ef7f4d3a1d499/raw/baffda78ffdcaf8ece87a76fb2bb3fd767820a3f/kube-dashboard.yaml

- name: Get node port
  shell: kubectl describe svc kubernetes-dashboard -n kube-system  | grep NodePort | grep -o '[0-9]*'
  register: result

- name: set node port
  set_fact:
    nodeport: "{{ result.stdout }}"

- name: Print master ip
  debug:
    msg: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

- name: Print nodeport
  debug:
    msg: "{{ nodeport }}"

- name: Print dashboard url for user
  debug:
    msg: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ nodeport }}"
    
- name: Ensure cbs user has access to kubernetes cluster
  shell: sudo cp /etc/kubernetes/admin.conf /home/"{{ ansible_ssh_user }}"/.kube/config
