---

- hosts: localhost
  tasks:
    - name: ssh-keygen
      shell: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
      args:
        creates: /root/.ssh/id_rsa
    - name: Set authorized key took from file
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
      register: pub_key
    - name: set authorization key
      set_fact:
        auth_key: "{{ pub_key['keyfile'] }}"

    - name: Update authorized key on all clients
      shell: sshpass -p "{{ hostvars[item].passwd }}" ssh-copy-id -i /root/.ssh/id_rsa.pub -o StrictHostKeyChecking=no "{{ hostvars[item].user }}"@{{ item }}
      with_items: "{{ groups.newnode }}"

- hosts: all
  tasks:

- hosts: localhost
  tasks:
    - include: "roles/common/tasks/add_new_node_ip_to_all_hosts.yml"

- name: Apply common configurations
  hosts: newnode
 
  roles:
    - common

- name: Get kubeadmin join details
  hosts: k8smaster
  tasks:
    - include: "roles/k8smaster/tasks/get_master_token.yml"

- name: Apply kubeadm join on new node
  hosts: newnode
  tasks:
    - name: new node
      shell: "{{ hostvars[item].kubeadmjoincmd }}"
      with_items: "{{ groups.k8smaster }}"
    - name: Wait for new node to join the cluster
      shell: sleep 30

- name: Get k8s cluster states
  hosts: k8smaster
  tasks:
    - name: Get k8s nodes info
      shell: kubectl get nodes
      register: result
    - debug: msg= "{{ result.stdout_lines }}"
