---

- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item].ansible_hostname }}"
    state: present
  with_items: "{{ groups.all }}"

- name: Verify /etc/hosts
  shell: cat /etc/hosts

- name: Reset kubeadm
  shell: kubeadm reset
  ignore_errors: yes
