---

- debug:
    msg: "{{ hostvars[inventory_hostname].ansible_all_ipv4_addresses }}"

- name: Update the OS
  shell: apt-get update -y
  ignore_errors: yes

- name: Update apt-transport-https
  shell: apt-get install apt-transport-https -y
  ignore_errors: yes

- name: exec bash
  shell: exec bash

- name: setenforce 0
  shell: setenforce 0
  ignore_errors: yes

- name: Disable firewalld
  shell: systemctl disable firewalld
  ignore_errors: yes

- name: Stop firewalld
  shell: systemctl stop firewalld
  ignore_errors: yes

- name: Copy k8s.conf @ /etc/sysctl.conf
  copy: src=k8s.conf dest=/etc/sysctl.conf

- name: Turn off swap
  shell: swapoff -a

- name: Swap disable
  shell: sed -i '/swap/s/^/#/g' /etc/fstab

#- name: Reboot the machine
#  shell: nohup bash -c "sleep 2s && shutdown -r now" &

- name: systemctl daemon-reload
  shell: systemctl daemon-reload

- name: Wait for machine to come back
  wait_for_connection:
    timeout: 240
    delay: 20

- name: Kubernetes for ubuntu
  shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

- name: Kubernetes for ubuntu
  shell: echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list

- name: Update the OS again
  shell: apt-get update -y
  ignore_errors: yes

- name: Remove docker-ce
  shell: apt-get purge --auto-remove docker-ce -y
  ignore_errors: yes

- name: Remove docker
  shell: apt-get purge --auto-remove docker -y
  ignore_errors: yes

- name: stop kubelet
  shell: systemctl stop kubelet
  ignore_errors: yes

- name: docker rm
  shell: docker rm -f -v $(docker ps -q)
  ignore_errors: yes

- name: find kubelet
  shell: find /var/lib/kubelet | xargs -n 1 findmnt -n -t tmpfs -o TARGET -T | uniq | xargs -r umount -v

- name: kubeadm reset 
  shell: kubeadm reset --skip-preflight-checks --force
  ignore_errors: yes

- name: kube purge
  shell: apt-get purge --auto-remove "{{ item }}" -y
  with_items:
    - kubeadm
    - kubectl
    - kubelet
    - kubernetes-cni
      #  shell:  dpkg --remove --force-all docker-ce docker kubeadm kubectl kubelet kubernetes-cni
  ignore_errors: yes

- name: autoremove
  shell: echo "y" | sudo apt-get autoremove

- name: rm kubernetes
  shell: rm -rf ~/.kube /etc/kubernetes /etc/systemd/system/kubelet.service.d /var/lib/kubelet /var/lib/etcd

- name: Install docker, kubelet, kubeadm, kubectl & kubernetes-cni latest version
  apt: name="{{ item }}" state=present
  with_items:
    - docker.io
    - kubelet
    - kubeadm 
    - kubectl
    - kubernetes-cni

- name: Start docker & kubelet
  shell: systemctl start docker && systemctl start kubelet

- name: Enable docker & kubelet
  shell: systemctl enable docker && systemctl enable kubelet
  
